<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKRAtKnr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKRAtKnr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKRAtKnr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKRAtKnr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKRAtKnr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KRAtKnr',
    'container.build_id' => '392d3f92',
    'container.build_time' => 1608472085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKRAtKnr');
